// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supersonic/cursor/proto/cursors.proto

#ifndef PROTOBUF_supersonic_2fcursor_2fproto_2fcursors_2eproto__INCLUDED
#define PROTOBUF_supersonic_2fcursor_2fproto_2fcursors_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace image {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_supersonic_2fcursor_2fproto_2fcursors_2eproto();
void protobuf_AssignDesc_supersonic_2fcursor_2fproto_2fcursors_2eproto();
void protobuf_ShutdownFile_supersonic_2fcursor_2fproto_2fcursors_2eproto();


enum CursorId {
  FILE_INPUT = 3,
  GENERATE = 4,
  REPEATING_BLOCK = 5,
  SELECTION_VECTOR_VIEW = 6,
  VIEW = 7,
  AGGREGATE_CLUSTERS = 8,
  BARRIER_SPLIT_READER = 9,
  BEST_EFFORT_GROUP_AGGREGATE = 10,
  BUFFERED_SPLIT_READER = 11,
  CANCELLATION_WATCH = 12,
  COALESCE = 13,
  COMPUTE = 15,
  FILTER = 16,
  FOREIGN_FILTER = 17,
  GROUP_AGGREGATE = 18,
  HASH_JOIN = 19,
  HYBRID_GROUP_FINAL_AGGREGATION = 20,
  HYBRID_GROUP_TRANSFORM = 21,
  LIMIT = 22,
  LOOKUP_JOIN = 23,
  MERGE_UNION_ALL = 24,
  PARALLEL_UNION = 25,
  PROJECT = 26,
  ROWID_MERGE_JOIN = 28,
  SCALAR_AGGREGATE = 29,
  SORT = 30,
  DECORATOR = 32,
  OWNERSHIP_TAKER = 33,
  READ_STATISTICS = 34,
  BARRIER_INJECTOR = 35,
  BARRIER_SWALLOWER = 36,
  BENCHMARK = 37,
  DEEP_COPYING = 38,
  INTERRUPTION_COUNTER = 39,
  TEST_DECORATOR = 40,
  VIEW_LIMITER = 41,
  UNKNOWN_ID = 42
};
bool CursorId_IsValid(int value);
const CursorId CursorId_MIN = FILE_INPUT;
const CursorId CursorId_MAX = UNKNOWN_ID;
const int CursorId_ARRAYSIZE = CursorId_MAX + 1;

const ::google::protobuf::EnumDescriptor* CursorId_descriptor();
inline const ::std::string& CursorId_Name(CursorId value) {
  return ::google::protobuf::internal::NameOfEnum(
    CursorId_descriptor(), value);
}
inline bool CursorId_Parse(
    const ::std::string& name, CursorId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CursorId>(
    CursorId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace image

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::container::CursorId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::container::CursorId>() {
  return ::container::CursorId_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_supersonic_2fcursor_2fproto_2fcursors_2eproto__INCLUDED
